import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { SessionProviderClient } from "@/components/SessionProviderClient";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderClient>
          <header className="w-full flex justify-between items-center p-4">
            <Link href="/" className="text-xl font-bold hover:underline">
              CHGK Trainer
            </Link>
            <Link href="/profile" className="text-sm font-medium hover:underline">
              Профиль
            </Link>
          </header>
          {children}
        </SessionProviderClient>
      </body>
    </html>
  );
}
